sudo: false
language: node_js
node_js:
  - '4'
  - '5'
before_install: "npm install babel-cli -g"
script: "npm run test:cov"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
